# Sử dụng image chính thức của Nginx
FROM nginx:latest

# Sao chép file index.html vào thư mục phục vụ web của Nginx
COPY index.html /usr/share/nginx/html/

# Mặc định Nginx sẽ chạy trên cổng 80
EXPOSE 80
