version: '3'

services:
  # Flask instance 1
  flask1:
    build:
      context: ./flask_app
      dockerfile: Dockerfile
    expose:
      - "5000"
    networks:
      - app_network

  # Flask instance 2
  flask2:
    build:
      context: ./flask_app
      dockerfile: Dockerfile
    expose:
      - "5000"
    networks:
      - app_network

  # Nginx Load Balancer
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - flask1
      - flask2
    networks:
      - app_network

networks:
  app_network:
    driver: bridge