version: '3'
services:
  node-app:
    build: .
    container_name: my-node-app
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
